### ISSUE TITLE
菫&蓳&堇，混用問題

### ISSUE THREAD

**Issue by fly6Liu** [TaiBON/checklister#143]
堇ㄐ一ㄣˇ，柔毛堇葉碎米薺(十字花科)、非洲堇(苦苣苔科)、堇寶蓮(桃金孃科)、堇菜科除三角葉**菫**菜
菫ㄐ一ㄣˇ，夏菫(母草科)、裡菫紫金牛(櫻草科)、三角葉菫菜(**堇**菜科)、罌粟科除球果紫**蓳**
蓳ㄐ一ㄣˋ，球果紫蓳(罌粟科)

**Comment by mutolisp** [comment]
謝謝，我有發現這個問題，我預計會統一使用「菫」，謝謝
