### ISSUE TITLE
黃杞、南仁五月茶、單刺苦櫧

### ISSUE THREAD

**Issue by kjungchao** [TaiBON/checklister#153]
黃杞屬名在Taibif是 Engelhardtia
Flora of Taiwan 是 Engelhardia
IPNI沒有查到 Engelhardtia
是否應更正為Engelhardia?

南仁五月茶在Flora of Taiwan 
學名是Antidesma hiiranense
但是Taibif沒有這個種
請問是被合併了嗎?

單刺苦櫧學名
在Taibif只列出forma
是否應列出變種小名?
Castanopsis cuspidata var. carlesii f. sessilis
或是採IPNI的Castanopsis cuspidata var. carlesii 

謝謝!

**Comment by mutolisp** [comment]
@kjungchao  
1. _Engelhardia_ 已更正了
2. 南仁五月茶應該是變更為 _Antidesma japonicum_ var. _japonicum_ (ref: http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:77167497-1)，我會把南仁五月茶刪除，以日本五月茶取代
3. 我傾向用二名制， _Castanopsis cuspidata_ var. _carlesii_

謝謝，

整理完一批更正新增物種後，會再更新資料庫，屆時請學姊再按選單的「資料庫」/「更新資料庫」即可
