### ISSUE TITLE
Newly naturalized species: Micranthemum micranthemoides, Ruellia squarrosa

### ISSUE THREAD

**Issue by mutolisp** [TaiBON/checklister#31]
# 臺灣2種新歸化植物－蔓枝蘆莉草與小蕊珍珠草

## Abstract

小蕊珍珠草(*Micranthemum micranthemoides*)與蔓枝蘆莉草(*Ruellia squarrosa*)為新歸化於臺灣中部之植物。本文描述這 2 種植物形態、解剖圖及彩 色照片外並報告其分布、生態及與近似種分類上之差異。

## To do

新增物種

## References
許再文 、蔣鎮宇 、黃朝慶 (2016) 臺灣2種新歸化植物－蔓枝蘆莉草與小蕊珍珠草。臺灣生物多樣性研究 18(2):123–130 [weblink](http://tesri.tesri.gov.tw/show_protect.php?volume=18&issue=2&page=123) [pdf](http://tesri.tesri.gov.tw/files/tesri_protect/tesri_journal_20160422094739/TW%20J.%20Bio%202016.18.2.%20123-130.pdf)

**Comment by chuckyfish** [comment]
小蕊珍珠草(Micranthemum micranthemoides)與蔓枝蘆莉草(Ruellia squarrosa)
中文名與俗名配錯了

**Comment by mutolisp** [comment]
thanks for your correction!
