### ISSUE TITLE
 Boraginaceae 包含Cordiaceae 和 Ehretiaceae

### ISSUE THREAD

**Issue by kjungchao** [TaiBON/checklister#75]
2016 APG IV  將這兩個科(Cordiaceae 和 Ehretiaceae)又併回去  Boraginaceae
但資料庫中還是分開的

(所有併入的科含 Codonaceae, Cordiaceae, Ehretiaceae, Lennoaceae, Wellstediaceae, Heliotropiaceae,
Hydrophyllaceae)

**Comment by mutolisp** [comment]
目前是先依照 Luebert (2016) Familial classification of the Boraginales 的處理（這篇剛好在 APG IV 出來之後才發表的，之後也許會再更正）
